# Define the base params


# Naming
cluster_template_name: "ec2-cluster-test"
cluster_id: 1

# Launch Location
region: "us-west-2"
az: "us-west-2c"

vpc_id : "vpc-09fe736b3807bbecf"
subnet_id: "subnet-016dd4822d0e200b1"


# AMI
ami_id: "ami-0b294f219d14e6a82"
ebs_snapshot_id: "snap-013f2dc8c2ecc97d9"
username: "ubuntu"

# EBS
volume_type: "gp2"
# iops: 5000
volume_gbs: 100

# Launch Settings
instance_type: "t3.nano"
node_count: 2

iam_ec2_role_name: "ec2-cluster-test-role"
key_name: "ec2-cluster-test"
security_group_ids:
  - "sg-08f2dd4548d863796" # armand-ssh



# EC2Cluster behavior args
cluster_create_timeout_secs: 600 # Fail after 10 minutes without an increase in the cluster size
ebs_optimized: No